export const prompts = [
  "Apple",
  "Banana",
  "Orange",
  "Strawberry",
  "Pineapple",
  "Watermelon",
  "Grapes",
  "Mango",
  "Peach",
  "Cherry",
  "Dog",
  "Cat",
  "Elephant",
  "Tiger",
  "Monkey",
  "Penguin",
  "Rabbit",
  "Horse",
  "Dolphin",
  "Giraffe",
  "Pizza",
  "Hamburger",
  "Ice cream",
  "French fries",
  "Chocolate cake",
  "Peanut butter",
  "Hot dog",
  "Chicken nuggets",
  "Grilled cheese",
  "Pancakes",
  "School bus",
  "Fire truck",
  "Bicycle",
  "Airplane",
  "Train station",
  "Race car",
  "Helicopter",
  "Motorcycle",
  "Taxi driver",
  "Rocket ship",
  "Sunny day",
  "Rainy weather",
  "Snowball fight",
  "Beach vacation",
  "Mountain hike",
  "Camping trip",
  "Birthday party",
  "Movie night",
  "Board game",
  "Swimming pool",
  "Happy birthday",
  "Good morning",
  "See you later",
  "Thank you",
  "You're welcome",
  "How are you",
  "I love pizza",
  "Nice to meet you",
  "Have a great day",
  "What's your name",
  "Purple elephant",
  "Dancing penguin",
  "Flying banana",
  "Sleepy tiger",
  "Magic carpet",
  "Rainbow unicorn",
  "Talking potato",
  "Giant cookie",
  "Invisible monkey",
  "Silly goose",
  "Open the door",
  "Close your eyes",
  "Jump up high",
  "Touch your nose",
  "Wave your hand",
  "Spin around",
  "Clap twice",
  "Sit down",
  "Stand up",
  "Take a picture",
  "Video game",
  "Computer mouse",
  "Mobile phone",
  "Headphones",
  "Television remote",
  "Keyboard shortcut",
  "Internet browser",
  "Social media",
  "Virtual reality",
  "Smart watch",
  "Treasure hunt",
  "Secret mission",
  "Lost treasure",
  "Hidden cave",
  "Pirate ship",
  "Space adventure",
  "Jungle explorer",
  "Time traveler",
  "Superhero costume",
  "Mystery box"
];